In [1]:
import pandas, os, numpy as np
import os, sklearn, pandas, numpy as np
from sklearn import svm
import skimage
from skimage import io, filters
from utils import utils # custom functions, in local environment
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## NN libs
import keras
from sklearn.decomposition import PCA
from keras.utils import to_categorical
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, Conv3D, MaxPool2D, Dropout, Flatten

Using TensorFlow backend.


In [3]:
import data, config, tfidf
from utils import io

 Dataset :: namedtuple(
  'info': pandas.df
  'labels': pandas.df('filename.txt': 'genre')
  'genres': ['genre'] # unique genres
  'label_dataset': SubDataset
  'sentiment_dataset': SubDataset
  'book_sentiment_words_list': ['filename']

 SubDataset :: namedtuple(
   'dict_index_to_label' = dict to convert label_index -> label_name
   'dict_label_to_index'= dict to convert label_name -> label_index



In [4]:
# info = pandas.read_csv(config.dataset_dir + 'final_data.csv')
dataset = data.init_dataset()
dataset.info.keys()

Index(['title', 'filename', 'title.1', 'author', 'release year', 'genre',
       'pos score', 'neg score', 'neu score', 'comp score', 'amt pos',
       'amt neg'],
      dtype='object')

In [5]:
dataset.info

title     filename  \
0                                  Jonah     3678.txt   
1                The Wind in the Willows      289.txt   
2                                  Akbar  40155-8.txt   
3                                Erewhon     1906.txt   
4                          Night and Day     1245.txt   
5                          She and Allan     5745.txt   
6                  The Amateur Cracksman      706.txt   
7                     Anne of Geierstein  44247-8.txt   
8                         A Tramp Abroad     5786.txt   
9                  Captives of the Flame    41905.txt   
10                      Madame de Mauves     7813.txt   
11               Five Weeks in a Balloon     3526.txt   
12                                  Tara    45430.txt   
13              The Mysteries of Udolpho     3268.txt   
14                                Clocks      855.txt   
15          A Child's History of England      699.txt   
16                            Green Eyes  45557-8.txt   
17                            Botticelli  39942-8.txt   
18                   The Longest Journey     2604.txt   
19     Down and Out in the Magic Kingdom   8086-8.txt   
20                              Meccania    44074.txt   
21                              Leinster    43096.txt   
22                        Off on a Comet   1353-8.txt   
23                       The Ivory Trail     5194.txt   
24                       Sketches by Boz      882.txt   
25                                Hunger   8387-8.txt   
26                Kilmeny of the Orchard     5341.txt   
27                             Narcissus  42533-8.txt   
28                           The Martian    40992.txt   
29         Further Chronicles of Avonlea   5340-8.txt   
..                                   ...          ...   
928                           Just David      440.txt   
929                    Jewels of Gwahlur  42236-8.txt   
930                              Physics  40175-0.txt   
931  Eight Hundred Leagues on the Amazon   3091-8.txt   
932                           The Forest   9376-8.txt   
933                                 Vera     1843.txt   
934            Further Adventures of Lad     2392.txt   
935                      The Woodlanders      482.txt   
936                   Anne of Geierstein    44247.txt   
937                The Red and the Black  44747-8.txt   
938                          Prince Otto    372-0.txt   
939                              Married     7956.txt   
940            Riders of the Purple Sage     1300.txt   
941               The Emerald City of Oz    41667.txt   
942                           Growing Up    42408.txt   
943                          O Pioneers!       24.txt   
944                            Jane Eyre     1260.txt   
945                           White Fang      910.txt   
946                                Murat     2755.txt   
947                 The Sorrows of Satan  42332-8.txt   
948                           On the Eve     6902.txt   
949                            Ruth Hall    40814.txt   
950               The Second Jungle Book     1937.txt   
951                              Spiders    44496.txt   
952                    The Mediterranean    41263.txt   
953                              Dorothy  40300-8.txt   
954                       Blood Brothers   8423-8.txt   
955               The Wallet of Kai Lung     1076.txt   
956            All Roads Lead to Calvary     2231.txt   
957                                Akbar    40155.txt   

                                 title.1  \
0                                  Jonah   
1                The Wind in the Willows   
2                                  Akbar   
3                                Erewhon   
4                          Night and Day   
5                          She and Allan   
6                  The Amateur Cracksman   
7                     Anne of Geierstein   
8                         A Tramp Abroad   
9                  Captives of the Flame   
10              

In [6]:
name = '7813.txt'
data.get_label(name, dataset.labels)

'Novella'

In [7]:
dataset.labels.keys()
dataset.labels['1005.txt'][0]

'Christian fiction'

In [8]:
train = dataset.book_sentiment_words_list[:10]
test = dataset.book_sentiment_words_list[10:20]

In [9]:
x_train, y_train = data.extract_all(dataset, train)
x_test, y_test = data.extract_all(dataset, test)

In [10]:
y_train

['Christian fiction',
 'Adventure novel',
 'Western novel',
 'Travel literature',
 'Comic novel',
 'Künstlerroman',
 'Adventure novel',
 'Fantasy novel',
 "Children's literature",
 'Adventure novel']

### Prepare the labels

Encode the labels to one-hot vectors

In [11]:
y_train, y_test = data.labels_to_vectors(dataset.label_dataset,y_train, y_test)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Convert tokenlist to vectors

### Using sentiment-wordlist

In [12]:
b = dataset.sentiment_dataset
a = 'a s d fp sks dk fsji sdf'.split(' ')
data.tokenlist_to_vector(a,b)

array([0.57735027, 0.        , 0.        ])

### Using polarization scores

In [13]:
data.polarization_scores_to_vector(dataset,'706.txt')

array([0.05957593, 0.04597156, 0.66307096, 0.02651661])

### Using NER scores

In [14]:
# ...

## Train a model
Although most of the input consists of classes, many classes will be correlated (e.g. related genres).
Therefore a neural network is chosen to model the data

In [25]:
def to_vector(x_train, dataset):
    x2 = []
    for filename, tokens in x_train:
        v1 = data.tokenlist_to_vector(tokens, dataset.sentiment_dataset)
        v2 = data.polarization_scores_to_vector(dataset, filename)
        v = np.append(v1, v2)
        x2.append(v)
    return np.stack(x2)

In [27]:
x_train2 = to_vector(x_train, dataset)
x_train2.shape

(10, 7)

In [29]:
n_samples = len(x_train2) # = length of the list of images (matrices)
input_shape = x_train2.shape[1:] # = shape of an individual image (matrix)
output_length = (y_train[0]).shape[0] # = length of an individual label
print(n_samples, input_shape)
print('output length', output_length)

10 (7,)
output length 158


In [54]:
def sequential(input_shape, output_length):
    model = Sequential()
    model.add(Dense(128, input_shape=input_shape))
    model.add(Activation('relu'))  # because relu is awesome
    model.add(Dense(output_length))
    model.add(Activation('softmax'))
    # in addition, return a function that displays information about the model
    return model, model.summary

In [55]:
# import models # src/models.py

model, summary = sequential(input_shape, output_length)
summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 128)               1024      
_________________________________________________________________
activation_3 (Activation)    (None, 128)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 158)               20382     
_________________________________________________________________
activation_4 (Activation)    (None, 158)               0         
Total params: 21,406
Trainable params: 21,406
Non-trainable params: 0
_________________________________________________________________


## Loss function
- Categorical cross-entropy loss

In [56]:
learning_rate = 0.01
optimizer = Adam(lr=learning_rate)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

## Finally train the model

In [57]:
# Compute a batch size
batch_size = round(n_samples / 10)
# n epochs = n iterations over all the training data
epochs = 5

In [58]:
model.fit(x_train2, y_train, epochs=epochs, batch_size=batch_size, validation_split=1/5)

Train on 8 samples, validate on 2 samples
Epoch 1/5
8/8 [==============================] - 0s 57ms/step - loss: 5.0421 - acc: 0.0000e+00 - val_loss: 4.8717 - val_acc: 0.0000e+00
Epoch 2/5
8/8 [==============================] - 0s 2ms/step - loss: 4.1552 - acc: 0.1250 - val_loss: 4.3556 - val_acc: 0.0000e+00
Epoch 3/5
8/8 [==============================] - 0s 3ms/step - loss: 2.8459 - acc: 0.1250 - val_loss: 4.4335 - val_acc: 0.0000e+00
Epoch 4/5
8/8 [==============================] - 0s 2ms/step - loss: 2.1163 - acc: 0.1250 - val_loss: 5.5491 - val_acc: 0.0000e+00
Epoch 5/5
8/8 [==============================] - 0s 2ms/step - loss: 2.0267 - acc: 0.2500 - val_loss: 6.1588 - val_acc: 0.5000


In [59]:
result_known_data = model.predict(x_train2)
result_known_data == y_train

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [60]:
result_known_data

array([[1.8631421e-05, 2.3759421e-05, 1.9479583e-05, ..., 1.8151064e-05,
        2.3767081e-05, 6.9395676e-02],
       [2.3281935e-05, 2.9353312e-05, 2.4164980e-05, ..., 2.2704815e-05,
        2.9492827e-05, 7.0404150e-02],
       [3.2635868e-05, 4.0770607e-05, 3.4019729e-05, ..., 3.1939140e-05,
        4.0833176e-05, 7.2843209e-02],
       ...,
       [2.9167664e-05, 3.6507561e-05, 3.0199690e-05, ..., 2.8357514e-05,
        3.6741229e-05, 7.1583681e-02],
       [1.3587793e-05, 1.7434430e-05, 1.4107607e-05, ..., 1.3219166e-05,
        1.7522842e-05, 6.7066565e-02],
       [3.0514009e-05, 3.8215148e-05, 3.1803043e-05, ..., 2.9817957e-05,
        3.8283291e-05, 7.2381467e-02]], dtype=float32)