In [1]:
import pandas, os, numpy as np
import os, sklearn, pandas, numpy as np
from sklearn import svm
import skimage
from skimage import io, filters
from utils import utils # custom functions, in local environment
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## NN libs
import keras
from sklearn.decomposition import PCA
from keras.utils import to_categorical
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, Conv3D, MaxPool2D, Dropout, Flatten

Using TensorFlow backend.


In [3]:
import data, config, tfidf, models
from utils import io

 Dataset :: namedtuple(
  'info': pandas.df
  'labels': pandas.df('filename.txt': 'genre')
  'genres': ['genre'] # unique genres
  'label_dataset': SubDataset
  'sentiment_dataset': SubDataset
  'book_sentiment_words_list': ['filename']

 SubDataset :: namedtuple(
   'dict_index_to_label' = dict to convert label_index -> label_name
   'dict_label_to_index'= dict to convert label_name -> label_index



In [4]:
# info = pandas.read_csv(config.dataset_dir + 'final_data.csv')
dataset = data.init_dataset()
dataset.info.keys()

Index(['title', 'filename', 'title.1', 'author', 'release year', 'genre',
       'pos score', 'neg score', 'neu score', 'comp score', 'amt pos',
       'amt neg'],
      dtype='object')

In [5]:
amt = 400
train = dataset.book_sentiment_words_list[:amt]
test = dataset.book_sentiment_words_list[amt:amt + amt]

In [6]:
x_train, y_train = data.extract_all(dataset, train)
x_test, y_test = data.extract_all(dataset, test)

In [7]:
dataset.labels

1005.txt  1024.txt 1027.txt 103.txt 1051.txt      1056.txt   106.txt  \
0  christian  adventur  western  travel    comic  knstlerroman  adventur   

  1066-0.txt 1080.txt 1081.txt   ...   9845-8.txt 9845.txt 9846-8.txt  \
0   children    satir    polit   ...          spi      spi    fantasi   

  9846.txt      9858-8.txt        9858.txt    9865-8.txt      9865.txt  \
0  fantasi  poetri magazin  poetri magazin  world war ii  world war ii   

  9909.txt 996.txt  
0   gothic   novel  

[1 rows x 744 columns]

In [8]:
dataset.info

title     filename  \
0                                  Jonah     3678.txt   
1             King--of the Khyber Rifles     6066.txt   
2                The Wind in the Willows      289.txt   
3                                  Akbar  40155-8.txt   
4                                Erewhon     1906.txt   
5                          Night and Day     1245.txt   
6                          She and Allan     5745.txt   
7                  The Amateur Cracksman      706.txt   
8                     Anne of Geierstein  44247-8.txt   
9                         A Tramp Abroad     5786.txt   
10                 Captives of the Flame    41905.txt   
11                      Madame de Mauves     7813.txt   
12               Five Weeks in a Balloon     3526.txt   
13                                  Tara    45430.txt   
14              The Mysteries of Udolpho     3268.txt   
15                   Notre-Dame de Paris     2610.txt   
16                                Clocks      855.txt   
17                            Green Eyes  45557-8.txt   
18                            Botticelli  39942-8.txt   
19                   The Longest Journey     2604.txt   
20     Down and Out in the Magic Kingdom   8086-8.txt   
21                              Meccania    44074.txt   
22                              Leinster    43096.txt   
23                        Off on a Comet   1353-8.txt   
24                       The Ivory Trail     5194.txt   
25                       Sketches by Boz      882.txt   
26                                Hunger   8387-8.txt   
27                Kilmeny of the Orchard     5341.txt   
28                             Narcissus  42533-8.txt   
29                           The Martian    40992.txt   
..                                   ...          ...   
885                           Just David      440.txt   
886                    Jewels of Gwahlur  42236-8.txt   
887                              Physics  40175-0.txt   
888  Eight Hundred Leagues on the Amazon   3091-8.txt   
889                           The Forest   9376-8.txt   
890                                 Vera     1843.txt   
891            Further Adventures of Lad     2392.txt   
892                      The Woodlanders      482.txt   
893                             Revenge!     8668.txt   
894                   Anne of Geierstein    44247.txt   
895                The Red and the Black  44747-8.txt   
896                          Prince Otto    372-0.txt   
897                              Married     7956.txt   
898            Riders of the Purple Sage     1300.txt   
899               The Emerald City of Oz    41667.txt   
900                           Growing Up    42408.txt   
901                            Jane Eyre     1260.txt   
902                           White Fang      910.txt   
903                                Murat     2755.txt   
904                 The Sorrows of Satan  42332-8.txt   
905                           On the Eve     6902.txt   
906                            Ruth Hall    40814.txt   
907               The Second Jungle Book     1937.txt   
908                              Spiders    44496.txt   
909                    The Mediterranean    41263.txt   
910                              Dorothy  40300-8.txt   
911                       Blood Brothers   8423-8.txt   
912               The Wallet of Kai Lung     1076.txt   
913            All Roads Lead to Calvary     2231.txt   
914                                Akbar    40155.txt   

                                 title.1  \
0                                  Jonah   
1             King--of the Khyber Rifles   
2                The Wind in the Willows   
3                                  Akbar   
4                                Erewhon   
5                          Night and Day   
6                          She and Allan   
7                  The Amateur Cracksman   
8                     Anne of Geierstein   
9                         A Tramp Abroad   
10              

In [9]:
y_train

['christian',
 'adventur',
 'western',
 'travel',
 'comic',
 'knstlerroman',
 'adventur',
 'children',
 'satir',
 'polit',
 'children',
 'children',
 'young adult',
 'science fiction',
 'satir',
 'detect',
 'dystopian',
 'horror',
 'children',
 'adventur',
 'unknown',
 'frame stori',
 'histor',
 'science',
 'cryptozoolog',
 'romance',
 'histor',
 'histor',
 'histor',
 'romantic',
 'romantic',
 'adventur',
 'nonsens poetri',
 'nonfict',
 'adventur',
 'adventur',
 'science fiction',
 'science fiction',
 'short stori',
 'lost world genr',
 'lost world genr',
 'fantasi',
 'fantasi',
 'science fiction',
 'literari realism',
 'literari realism',
 'children',
 'novel',
 'novel',
 'novel',
 'histor',
 'thriller',
 'children',
 'nonfict',
 'fantasi',
 'bildungsroman',
 'nonprofit',
 'biographi',
 'autobiographi',
 'fantasi',
 'fantasi',
 'novel',
 'novel',
 'literari realism',
 'juvenil',
 'novel of manner',
 'black comedi',
 'mysteri',
 'science fiction',
 'unknown',
 'histor',
 'romance',
 's

### Prepare the labels

Encode the labels to one-hot vectors

In [10]:
y_train, y_test = data.labels_to_vectors(dataset.label_dataset,y_train, y_test)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Convert tokenlist to vectors

### Using sentiment-wordlist

In [11]:
b = dataset.sentiment_dataset
a = 'a s d fp sks dk fsji sdf'.split(' ')
data.tokenlist_to_vector(a,b)

array([0., 0., 0., ..., 0., 0., 0.])

### Using polarization scores

In [12]:
data.polarization_scores_to_vector(dataset,'706.txt')

array([0.05957593, 0.04597156, 0.66307096, 0.02651661])

### Using NER scores

In [13]:
# ...

## Train a model
Although most of the input consists of classes, many classes will be correlated (e.g. related genres).
Therefore a neural network is chosen to model the data

In [14]:
x_train2 = models.to_vector(x_train, dataset)
x_train2.shape

(100, 5096)

In [15]:
n_samples = len(x_train2) # = length of the list of images (matrices)
input_shape = x_train2.shape[1:] # = shape of an individual image (matrix)
output_length = (y_train[0]).shape[0] # = length of an individual label
print(n_samples, input_shape)
print('output length', output_length)

100 (5096,)
output length 113


In [16]:
# import models # src/models.py
dropout = 0.01
model, summary = models.sequential(input_shape, output_length, dropout)
summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 255)               1299735   
_________________________________________________________________
dropout_1 (Dropout)          (None, 255)               0         
_________________________________________________________________
activation_1 (Activation)    (None, 255)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 113)               28928     
_________________________________________________________________
activation_2 (Activation)    (None, 113)               0         
Total params: 1,328,663
Trainable params: 1,328,663
Non-trainable params: 0
_________________________________________________________________


## Loss function
- Categorical cross-entropy loss

In [17]:
learning_rate = 0.01
optimizer = Adam(lr=learning_rate)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

## Finally train the model

In [18]:
# Compute a batch size
batch_size = round(n_samples / 10)
# n epochs = n iterations over all the training data
epochs = 9

In [19]:
model.fit(x_train2, y_train, epochs=epochs, batch_size=batch_size, validation_split=1/5)

Train on 80 samples, validate on 20 samples
Epoch 1/9
80/80 [==============================] - 1s 8ms/step - loss: 4.5587 - acc: 0.0375 - val_loss: 4.5572 - val_acc: 0.0500
Epoch 2/9
80/80 [==============================] - 0s 3ms/step - loss: 3.1599 - acc: 0.1500 - val_loss: 5.3454 - val_acc: 0.0000e+00
Epoch 3/9
80/80 [==============================] - 0s 3ms/step - loss: 2.6168 - acc: 0.3125 - val_loss: 5.9355 - val_acc: 0.0500
Epoch 4/9
80/80 [==============================] - 0s 3ms/step - loss: 2.0750 - acc: 0.5250 - val_loss: 5.9399 - val_acc: 0.0500
Epoch 5/9
80/80 [==============================] - 0s 3ms/step - loss: 1.5855 - acc: 0.6000 - val_loss: 6.1152 - val_acc: 0.0500
Epoch 6/9
80/80 [==============================] - 0s 3ms/step - loss: 1.0661 - acc: 0.7750 - val_loss: 6.4840 - val_acc: 0.0500
Epoch 7/9
80/80 [==============================] - 0s 3ms/step - loss: 0.6820 - acc: 0.9125 - val_loss: 6.8072 - val_acc: 0.1000
Epoch 8/9
80/80 [==============================] 

In [20]:
result_known_data = model.predict(x_train2)
result_known_data == y_train

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [21]:
i = result_known_data[0].argmax()
result_known_data[0][i]

0.9290103

In [22]:
# data.y_to_label_dict(dataset,result_known_data[0])

In [23]:
all_, best = data.decode_y(dataset, result_known_data[0])
best

['christian']

In [24]:
correct, incorrect = data.analyse_ml_result(dataset, y_train, result_known_data)
print(correct/float(incorrect + correct), correct, incorrect, correct+incorrect)

0.82 82 18 100


In [25]:
r = model.predict(models.to_vector(x_test, dataset))
correct, incorrect = data.analyse_ml_result(dataset, y_test, r, 1)
print(correct/float(incorrect + correct), correct, incorrect, correct+incorrect)

0.13 13 87 100


In [26]:
r = model.predict(models.to_vector(x_test, dataset))
correct, incorrect = data.analyse_ml_result(dataset, y_test, r, 5)
print(correct/float(incorrect + correct), correct, incorrect, correct+incorrect)

0.24 24 76 100
